services:
  app:
    image: dev-frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: dev-frontend

# docker compose -f docker-compose.dev.yml up